// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NganHangDeThi.Data.DataContext;

#nullable disable

namespace NganHangDeThi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205031418_AddBatchIdForDeThi")]
    partial class AddBatchIdForDeThi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NganHangDeThi.Data.Entity.CauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuongId")
                        .HasColumnType("int");

                    b.Property<bool>("DaRaDe")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<int>("MucDo")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuongId");

                    b.HasIndex("ParentId");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.CauTraLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauHoiId")
                        .HasColumnType("int");

                    b.Property<bool>("DaoViTri")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ViTriGoc")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("CauTraLoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.ChiTietCauTraLoiTrongDeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChiTietDeThiId")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ViTri")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietDeThiId");

                    b.ToTable("ChiTietCauTraLoiTrongDeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.ChiTietDeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauHoiId")
                        .HasColumnType("int");

                    b.Property<int>("DeThiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeThiId");

                    b.HasIndex("CauHoiId", "DeThiId")
                        .IsUnique();

                    b.ToTable("ChiTietDeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.ChiTietMaTran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuongId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiCauHoi")
                        .HasColumnType("int");

                    b.Property<int>("MaTranId")
                        .HasColumnType("int");

                    b.Property<int>("MucDoCauHoi")
                        .HasColumnType("int");

                    b.Property<int>("SoCau")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuongId");

                    b.HasIndex("MaTranId");

                    b.ToTable("ChiTietMaTran");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.Chuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViTri")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.ToTable("Chuong");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.DeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaThi")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<int>("MaDe")
                        .HasColumnType("int");

                    b.Property<int>("MaTranId")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianLamBai")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("MaTranId");

                    b.HasIndex("MonHocId");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GVCN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.MaTran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianCapNhatGanNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MaTran");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.MonHocThuocLop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LopHocId")
                        .HasColumnType("int");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("MonHocId");

                    b.ToTable("MonHocThuocLop");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.CauHoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.Chuong", "Chuong")
                        .WithMany("DsCauHoi")
                        .HasForeignKey("ChuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entity.CauHoi", "Parent")
                        .WithMany("DsCauHoiCon")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Chuong");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.CauTraLoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.CauHoi", "CauHoi")
                        .WithMany("DsCauTraLoi")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.ChiTietCauTraLoiTrongDeThi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.ChiTietDeThi", "ChiTietDeThi")
                        .WithMany("DsDapAnTrongDe")
                        .HasForeignKey("ChiTietDeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.ChiTietDeThi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entity.DeThi", "DeThi")
                        .WithMany("DsChiTietDeThi")
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("DeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.ChiTietMaTran", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.Chuong", "Chuong")
                        .WithMany()
                        .HasForeignKey("ChuongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entity.MaTran", "MaTran")
                        .WithMany("DsChiTietMaTran")
                        .HasForeignKey("MaTranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuong");

                    b.Navigation("MaTran");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.Chuong", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.MonHoc", "MonHoc")
                        .WithMany("DsChuong")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.DeThi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.LopHoc", "LopHoc")
                        .WithMany("DsDeThi")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entity.MaTran", "MaTran")
                        .WithMany("DsDeThi")
                        .HasForeignKey("MaTranId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entity.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("MaTran");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.MonHocThuocLop", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entity.LopHoc", "LopHoc")
                        .WithMany("DsMonHoc")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entity.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.CauHoi", b =>
                {
                    b.Navigation("DsCauHoiCon");

                    b.Navigation("DsCauTraLoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.ChiTietDeThi", b =>
                {
                    b.Navigation("DsDapAnTrongDe");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.Chuong", b =>
                {
                    b.Navigation("DsCauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.DeThi", b =>
                {
                    b.Navigation("DsChiTietDeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.LopHoc", b =>
                {
                    b.Navigation("DsDeThi");

                    b.Navigation("DsMonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.MaTran", b =>
                {
                    b.Navigation("DsChiTietMaTran");

                    b.Navigation("DsDeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entity.MonHoc", b =>
                {
                    b.Navigation("DsChuong");
                });
#pragma warning restore 612, 618
        }
    }
}
