// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NganHangDeThi.Data;

#nullable disable

namespace NganHangDeThi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812101924_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CaiDat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DinhDangNgayGio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HienThiXacNhanThoat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CaiDat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DinhDangNgayGio = "dd/MM/yyyy HH:mm",
                            HienThiXacNhanThoat = true
                        });
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChuongId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("DiemToiDa")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("FileImportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiCauHoi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MucDoCauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NhomCauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDungUnsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThuTuTrongNhom")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChuongId");

                    b.HasIndex("DaXoa");

                    b.HasIndex("FileImportId");

                    b.HasIndex("LoaiCauHoi");

                    b.HasIndex("MucDoCauHoiId");

                    b.HasIndex("NhomCauHoiId");

                    b.ToTable("CauHoi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CauHoiTuLuanY", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenY")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThangDiem")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("CauHoiTuLuanY", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Chuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonHocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenChuongUnsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThuTu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId", "ThuTu")
                        .IsUnique();

                    b.ToTable("Chuong", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.ChuongTrinhHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonHocId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NamHoc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("LopId", "MonHocId")
                        .IsUnique();

                    b.ToTable("ChuongTrinhHoc", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.DeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HocKyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LopId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaTranDeThiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("LopId");

                    b.HasIndex("MaTranDeThiId", "MaDe")
                        .IsUnique();

                    b.ToTable("DeThi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.DeThiCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeThiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThuTuPhuongAnDaTron")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThuTuTrongDe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("DeThiId", "CauHoiId")
                        .IsUnique();

                    b.HasIndex("DeThiId", "ThuTuTrongDe")
                        .IsUnique();

                    b.ToTable("DeThiCauHoi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.FileImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChuongId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DuongDanLuuTru")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MonHocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NguoiImport")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoCauLoi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoCauThanhCong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenFileGoc")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("TongSoCauNhanDien")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChuongId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MonHocId");

                    b.ToTable("FileImport", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.HinhAnhCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NhomCauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhuongAnTraLoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuTu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViTri")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("NhomCauHoiId");

                    b.HasIndex("PhuongAnTraLoiId");

                    b.ToTable("HinhAnhCauHoi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.HocKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NienKhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NienKhoaId");

                    b.ToTable("HocKy", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Khoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoaUnSign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.LoiImportCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoanVanBanGoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileImportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDungLoi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViTriCauTrongFile")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileImportId");

                    b.ToTable("LoiImportCauHoi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Lop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaLop")
                        .IsUnique();

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MaTranChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChuongId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoaiCauHoi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaTranDeThiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MucDoCauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongCau")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChuongId");

                    b.HasIndex("MucDoCauHoiId");

                    b.HasIndex("MaTranDeThiId", "ChuongId", "MucDoCauHoiId", "LoaiCauHoi")
                        .IsUnique();

                    b.ToTable("MaTranChiTiet", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaTranChiTiet_SoLuongCauDuong", "SoLuongCau > 0");
                        });
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MaTranDeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonHocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenMaTran")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.ToTable("MaTranDeThi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenMonUnSign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MucDoCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaSo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenMucDo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThuTu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaSo")
                        .IsUnique();

                    b.ToTable("MucDoCauHoi", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaSo = 2,
                            TenMucDo = "Dễ",
                            ThuTu = 1
                        },
                        new
                        {
                            Id = 2,
                            MaSo = 3,
                            TenMucDo = "Trung bình",
                            ThuTu = 2
                        },
                        new
                        {
                            Id = 3,
                            MaSo = 4,
                            TenMucDo = "Khó",
                            ThuTu = 3
                        });
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.NhomCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChuongId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileImportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiNhom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDungDuLieuChung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChuongId");

                    b.HasIndex("FileImportId");

                    b.ToTable("NhomCauHoi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.NienKhoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNienKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenNienKhoa")
                        .IsUnique();

                    b.ToTable("NienKhoa", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.PhuongAnTraLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CauHoiId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KhongHoanVi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<char>("KyTuNhan")
                        .HasColumnType("char(1)");

                    b.Property<bool>("LaDapAnDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThuTu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId", "KyTuNhan")
                        .IsUnique();

                    b.ToTable("PhuongAnTraLoi", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CauHoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Chuong", "Chuong")
                        .WithMany()
                        .HasForeignKey("ChuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.FileImport", "FileImport")
                        .WithMany("DanhSachCauHoiDaLuu")
                        .HasForeignKey("FileImportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NganHangDeThi.Data.Entities.MucDoCauHoi", "MucDoCauHoi")
                        .WithMany("DanhSachCauHoi")
                        .HasForeignKey("MucDoCauHoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NganHangDeThi.Data.Entities.NhomCauHoi", "NhomCauHoi")
                        .WithMany("DanhSachCauHoiCon")
                        .HasForeignKey("NhomCauHoiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chuong");

                    b.Navigation("FileImport");

                    b.Navigation("MucDoCauHoi");

                    b.Navigation("NhomCauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CauHoiTuLuanY", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.CauHoi", "CauHoi")
                        .WithMany("DanhSachY")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Chuong", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.MonHoc", "MonHoc")
                        .WithMany("DanhSachChuong")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.ChuongTrinhHoc", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Lop", "Lop")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.DeThi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NganHangDeThi.Data.Entities.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NganHangDeThi.Data.Entities.MaTranDeThi", "MaTranDeThi")
                        .WithMany("DanhSachDeThi")
                        .HasForeignKey("MaTranDeThiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("Lop");

                    b.Navigation("MaTranDeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.DeThiCauHoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.DeThi", "DeThi")
                        .WithMany("DanhSachCauHoi")
                        .HasForeignKey("DeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("DeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.FileImport", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Chuong", "Chuong")
                        .WithMany()
                        .HasForeignKey("ChuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chuong");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.HinhAnhCauHoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.CauHoi", "CauHoi")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NganHangDeThi.Data.Entities.NhomCauHoi", "NhomCauHoi")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("NhomCauHoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NganHangDeThi.Data.Entities.PhuongAnTraLoi", "PhuongAnTraLoi")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("PhuongAnTraLoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CauHoi");

                    b.Navigation("NhomCauHoi");

                    b.Navigation("PhuongAnTraLoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.HocKy", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.NienKhoa", "NienKhoa")
                        .WithMany("DsHocKy")
                        .HasForeignKey("NienKhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NienKhoa");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.LoiImportCauHoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.FileImport", "FileImport")
                        .WithMany("DanhSachLoi")
                        .HasForeignKey("FileImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileImport");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Lop", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Khoa", "Khoa")
                        .WithMany("DanhSachLop")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MaTranChiTiet", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Chuong", "Chuong")
                        .WithMany()
                        .HasForeignKey("ChuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.MaTranDeThi", "MaTranDeThi")
                        .WithMany("DanhSachChiTiet")
                        .HasForeignKey("MaTranDeThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.MucDoCauHoi", "MucDoCauHoi")
                        .WithMany()
                        .HasForeignKey("MucDoCauHoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chuong");

                    b.Navigation("MaTranDeThi");

                    b.Navigation("MucDoCauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MaTranDeThi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MonHoc", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Khoa", "Khoa")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.NhomCauHoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Chuong", "Chuong")
                        .WithMany()
                        .HasForeignKey("ChuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.FileImport", "FileImport")
                        .WithMany("DanhSachNhomDaLuu")
                        .HasForeignKey("FileImportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chuong");

                    b.Navigation("FileImport");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.PhuongAnTraLoi", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.CauHoi", "CauHoi")
                        .WithMany("DanhSachPhuongAn")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CauHoi", b =>
                {
                    b.Navigation("DanhSachHinhAnh");

                    b.Navigation("DanhSachPhuongAn");

                    b.Navigation("DanhSachY");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.DeThi", b =>
                {
                    b.Navigation("DanhSachCauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.FileImport", b =>
                {
                    b.Navigation("DanhSachCauHoiDaLuu");

                    b.Navigation("DanhSachLoi");

                    b.Navigation("DanhSachNhomDaLuu");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Khoa", b =>
                {
                    b.Navigation("DanhSachLop");

                    b.Navigation("DanhSachMonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Lop", b =>
                {
                    b.Navigation("DanhSachMonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MaTranDeThi", b =>
                {
                    b.Navigation("DanhSachChiTiet");

                    b.Navigation("DanhSachDeThi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MonHoc", b =>
                {
                    b.Navigation("DanhSachChuong");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MucDoCauHoi", b =>
                {
                    b.Navigation("DanhSachCauHoi");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.NhomCauHoi", b =>
                {
                    b.Navigation("DanhSachCauHoiCon");

                    b.Navigation("DanhSachHinhAnh");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.NienKhoa", b =>
                {
                    b.Navigation("DsHocKy");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.PhuongAnTraLoi", b =>
                {
                    b.Navigation("DanhSachHinhAnh");
                });
#pragma warning restore 612, 618
        }
    }
}
