// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NganHangDeThi.Data;

#nullable disable

namespace NganHangDeThi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726144855_AddHocKyTable")]
    partial class AddHocKyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CaiDat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DinhDangNgayGio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HienThiXacNhanThoat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CaiDat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DinhDangNgayGio = "dd/MM/yyyy HH:mm",
                            HienThiXacNhanThoat = true
                        });
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Chuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonHocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThuTu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId", "ThuTu")
                        .IsUnique();

                    b.ToTable("Chuong", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.ChuongTrinhHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonHocId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NamHoc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("LopId", "MonHocId")
                        .IsUnique();

                    b.ToTable("ChuongTrinhHoc", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.HocKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NienKhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NienKhoaId");

                    b.ToTable("HocKy", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Khoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoaUnSign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaKhoa")
                        .IsUnique();

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Lop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaLop")
                        .IsUnique();

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenMonUnSign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.NienKhoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNienKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenNienKhoa")
                        .IsUnique();

                    b.ToTable("NienKhoa", (string)null);
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Chuong", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.MonHoc", "MonHoc")
                        .WithMany("DanhSachChuong")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.ChuongTrinhHoc", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Lop", "Lop")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NganHangDeThi.Data.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.HocKy", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.NienKhoa", "NienKhoa")
                        .WithMany("DsHocKy")
                        .HasForeignKey("NienKhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NienKhoa");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Lop", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Khoa", "Khoa")
                        .WithMany("DanhSachLop")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MonHoc", b =>
                {
                    b.HasOne("NganHangDeThi.Data.Entities.Khoa", "Khoa")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Khoa", b =>
                {
                    b.Navigation("DanhSachLop");

                    b.Navigation("DanhSachMonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.Lop", b =>
                {
                    b.Navigation("DanhSachMonHoc");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.MonHoc", b =>
                {
                    b.Navigation("DanhSachChuong");
                });

            modelBuilder.Entity("NganHangDeThi.Data.Entities.NienKhoa", b =>
                {
                    b.Navigation("DsHocKy");
                });
#pragma warning restore 612, 618
        }
    }
}
