// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NganHangDeThi.Data;

#nullable disable

namespace NganHangDeThi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719110526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NganHangDeThi.Data.Entities.CaiDat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HienThiXacNhanThoat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CaiDat", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
